linux-user: avoid -Werror=int-in-bool-context
This is a backport of upstream QEMU commit db05b0d21ec1e0532cf5f5103ae6520a838d96f9,
which fixes the compilation error with GCC 14.

Upstream commit:
https://gitlab.com/qemu-project/qemu/-/commit/db05b0d21ec1e0532cf5f5103ae6520a838d96f9

Original commit message:
    linux-user: avoid -Werror=int-in-bool-context

    linux-user is failing to compile on Fedora 43:

    ../linux-user/strace.c:57:66: error: enum constant in boolean context [-Werror=int-in-bool-context]
       57 | #define FLAG_BASIC(V, M, N)      { V, M | QEMU_BUILD_BUG_ON_ZERO(!(M)), N }

    The warning does not seem to be too useful and we could even disable it,
    but the workaround is simple in this case.

    Cc: qemu-stable@nongnu.org
    Cc: Richard Henderson <richard.henderson@linaro.org>
    Reviewed-by: Daniel P. Berrangé <berrange@redhat.com>
    Signed-off-by: Paolo Bonzini <pbonzini@redhat.com>

Signed-off-by: Hui Li <lihui@loongson.cn>